# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration related to self-hosted runner.
self-hosted-runner:
  labels:
    - "windows-x86-n2-16"
    - "linux-x86-n2-16"
    - "linux-arm64-c4a-16"
    - "linux-x86-g2-48-l4-4gpu"
